version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_POSTGRES}
      - POSTGRES_USER=${USER_POSTGRES}
      - POSTGRES_PASSWORD=${PASSWORD_POSTGRES}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${CORREO_PG}
      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD_PG}
    ports:
      - "5050:80"

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=${BD_MYSQL}
      - MYSQL_USER=${USER_MYSQL}
      - MYSQL_ROOT_PASSWORD=${PASSWORD_MYSQL}
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD_MYSQL}
      - PMA_HOST=mysql
    ports:
      - "8080:80"
